### ISSUE TITLE
False positive

### ISSUE THREAD

**Issue by fmarier** [brave/security-action#342]
Reference: https://github.com/brave/brave-core/pull/19479#discussion_r1327864195

![Screenshot from 2023-09-18 10-28-42](https://github.com/brave/security-action/assets/167821/306ba098-9b55-40a4-8c44-15f34d44c14b)

That's not deleting something that was allocated, it's removing the default implementation inherited from a base class.

# Proposed Solution

- [ ] Remove the rule
- [x] Fork and improve the rule

**Comment by bcaller** [comment]
Using the experimental C++ engine,

```yaml
  - patterns:
    - pattern: delete($PTR);
    - pattern-not-inside: |
        $PTR = new $OBJ;
        ...
        delete($PTR);
```

is matching

```cpp
SecureDnsCounter& operator=(const SecureDnsCounter&) = delete;
```

despite there not being a pointer involved.

The rule was designed to find things like:

```cpp
	int *ptr;
	ptr = (int*)malloc(sizeof(int));

	// ruleid: raptor-mismatched-memory-management-cpp
	delete ptr;
```

but as mentioned in the message, it will generate false positives.

Would excluding this rule from `.h` header files help, or should we just scrap that pattern?

Source: [yaml](https://github.com/0xdea/semgrep-rules/blob/main/c/mismatched-memory-management-cpp.yaml) | [tests](https://github.com/0xdea/semgrep-rules/blob/main/c/mismatched-memory-management-cpp.cpp)

**Comment by bcaller** [comment]
Alternatively, adding

```yaml
    - metavariable-regex:
        metavariable: $PTR
        regex: .
```

would require a named pointer.
