### ISSUE TITLE
Port the C/C++ ruleset

### ISSUE THREAD

**Issue by thypon** [brave/security-action#69]
https://security.humanativaspa.it/semgrep-ruleset-for-c-c-vulnerability-research/

The task is both porting these rules in steps AND supervising `brave-core` while we start to find these issues

**Comment by thypon** [comment]
Dangling casts which we should catch:

```
rules:
- id: cast signed to unsigned (C/C++)
  patterns:
    - pattern: ($CAST)($TYPE $X)
    - metavariable-regex:
        metavariable: $CAST
        regex: ^(u.*)$
    - metavariable-regex:
        metavariable: $TYPE
        regex: ^([^u].*)$
  message: Semgrep found a cast from $TYPE (signed) to $CAST.
  languages: [cpp, c]
  severity: WARNING
```

For arithmetic in general we should use something like:

```
base::CheckAdd(value1, value2).AssignIfValid(&result) 
```
